accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.Login.as_view(), name='login'),
    path('register/', views.Register.as_view(), name='register'),
    path('registration-success/', views.RegistrationSuccess.as_view(),
         name='registration-success'),
    path('logout/', views.logoutUser, name='logout'),
    path('reset-password/', auth_views.PasswordResetView.as_view(
        template_name="accounts/reset-password.html"), name="reset_password"),
    path('reset-password-sent/', auth_views.PasswordResetDoneView.as_view(
        template_name="accounts/reset-password-sent.html"), name="password_reset_done"),
    path('reset-password-confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name="accounts/reset-password-confirm.html"), name="password_reset_confirm"),
    path('reset-password-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name="accounts/reset-password-complete.html"), name="password_reset_complete"),
    path('profile/', views.AccountProfile.as_view(), name='profile'),
    path('administrator/staff/', views.AdminRegisterSuperuser.as_view(),
         name='admin-staff'),
    path('staff/delete/<int:staff_id>',
         views.deleteStaff, name='delete-staff'),
    path('administrator/admin-profile/',
         views.AccountProfileAdmin.as_view(), name='admin-profile'),
]

event_registration_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('administrator/', include('administrator.urls')),
    path('member/', include('member.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

member/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static

urlpatterns = [
    path('dashboard', views.MemberDashboard.as_view(),
         name='member-dashboard'),
    path('events/find', views.FindEvent.as_view(),
         name='find-event'),
    path('events/event/<int:event_id>', views.ViewEvent.as_view(),
         name='view-event'),
    path('events/event/register/<int:event_id>',
         views.registerEvent, name='register-event'),
    path('events/event/unregister/<int:event_id>',
         views.unregisterEvent, name='unregister-event'),
    path('events/event/confirm-attendance/<int:event_id>',
         views.confirmAttendance, name='confirm-attendance'),
    path('events/event/register/form/<int:event_id>', views.PaidRegistration.as_view(),
         name='paid-registration'),
    path('events/joined', views.EventsJoined.as_view(),
         name='find-event'),
    path('transactions', views.Transactions.as_view(),
         name='transactions'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    profile_pic = models.ImageField(null=True, blank=True)
    affiliation = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.user.username

accounts/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username',
                  'email', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super(CreateUserForm, self).__init__(*args, **kwargs)

        self.fields['first_name'].widget.attrs.update(
            {'autofocus': 'autofocus', 'class': 'form-control', 'placeholder': 'First Name'})
        self.fields['last_name'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Last Name'})
        self.fields['username'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Username'})
        self.fields['email'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Email'})
        self.fields['password1'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Password'})
        self.fields['password2'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Confirm Password'})


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ['user']

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields['affiliation'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Affiliation'})


class CreateSuperUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username',
                  'email', 'password1', 'password2', 'is_superuser', 'is_staff']

    def __init__(self, *args, **kwargs):
        super(CreateSuperUserForm, self).__init__(*args, **kwargs)

        self.fields['first_name'].widget.attrs.update(
            {'autofocus': 'autofocus', 'class': 'form-control', 'placeholder': 'First Name'})
        self.fields['last_name'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Last Name'})
        self.fields['username'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Username'})
        self.fields['email'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Email'})
        self.fields['password1'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Password'})
        self.fields['password2'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Confirm Password'})

accounts/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.http import HttpResponse
from .forms import CreateUserForm, ProfileForm, CreateSuperUserForm
from .models import *
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.hashers import make_password
from .decorators import *

# Create your views here.


class Login(View):
    @method_decorator(unauthenticated_user)
    def get(self, request, *args, **kwargs):
        return render(request, template_name='accounts/login.html', context={})

    @method_decorator(unauthenticated_user)
    def post(self, request, *args, **kwargs):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if user.is_superuser:
                return redirect('/administrator/dashboard')
            else:
                return redirect('/member/dashboard')
        else:
            messages.info(request, 'Username or Password is incorrect.')
        return render(request, template_name='accounts/login.html', context={})


@login_required(login_url='/')
def logoutUser(request):
    logout(request)
    return redirect('/')


class Register(View):
    @method_decorator(unauthenticated_user)
    def get(self, request, *args, **kwargs):
        form = CreateUserForm()
        return render(request, template_name='accounts/register.html', context={'form': form})

    @method_decorator(unauthenticated_user)
    def post(self, request, *args, **kwargs):
        form = CreateUserForm(request.POST)

        if form.is_valid():
            user = form.save()

            profile = Profile(user=user)
            profile.save()
            return redirect('/registration-success/')

        else:
            messages.error(request, 'There was an error.')
        return render(request, template_name='accounts/register.html', context={'form': form})


class RegistrationSuccess(View):
    @method_decorator(unauthenticated_user)
    def get(self, request, *args, **kwargs):
        return render(request, template_name='accounts/registration-success.html', context={})


class AccountProfile(View):
    @method_decorator(login_required(login_url='/'))
    def get(self, request, *args, **kwargs):
        user = request.user
        profile = Profile.objects.get(user=user)

        form = ProfileForm(instance=profile)

        return render(request, template_name='accounts/profile.html', context={'form': form})

    @method_decorator(login_required(login_url='/'))
    def post(self, request, *args, **kwargs):
        user = request.user
        user_instance = Profile.objects.get(user=user)
        account_instance = User.objects.get(id=user.id)

        form = ProfileForm(request.POST, request.FILES, instance=user_instance)

        if form.is_valid():
            form.save()

            first_name = request.POST["first_name"]
            last_name = request.POST["last_name"]
            email = request.POST["email"]
            username = request.POST["username"]

            account_instance.first_name = first_name
            account_instance.last_name = last_name
            account_instance.email = email
            account_instance.username = username

            account_instance.save()

            messages.add_message(request,
                                 messages.SUCCESS,
                                 'Your profile information was saved successfully.')

            return redirect("/profile")

        else:
            messages.error(
                request, 'There was an error saving in your profile information.')
        return redirect("/profile")


class AccountProfileAdmin(View):
    @method_decorator(login_required(login_url='/'))
    def get(self, request, *args, **kwargs):
        user = request.user
        profile = Profile.objects.get(user=user)

        form = ProfileForm(instance=profile)

        return render(request, template_name='accounts/profile-admin.html', context={'form': form})

    @method_decorator(login_required(login_url='/'))
    def post(self, request, *args, **kwargs):
        user = request.user
        user_instance = Profile.objects.get(user=user)
        account_instance = User.objects.get(id=user.id)

        form = ProfileForm(request.POST, request.FILES, instance=user_instance)

        if form.is_valid():
            form.save()

            first_name = request.POST["first_name"]
            last_name = request.POST["last_name"]
            email = request.POST["email"]
            username = request.POST["username"]

            account_instance.first_name = first_name
            account_instance.last_name = last_name
            account_instance.email = email
            account_instance.username = username

            account_instance.save()

            messages.add_message(request,
                                 messages.SUCCESS,
                                 'Your profile information was saved successfully.')

            return redirect("/administrator/admin-profile")

        else:
            messages.error(
                request, 'There was an error saving in your profile information.')
        return redirect("/profile")


class AdminRegisterSuperuser(View):
    @method_decorator(login_required(login_url='/'))
    @method_decorator(admin_only())
    def get(self, request, *args, **kwargs):
        tmp_password = make_password('')
        form = CreateSuperUserForm(
            initial={'password1': tmp_password, 'password2': tmp_password, 'is_superuser': True, 'is_staff': True})
        form.fields['password1'].widget.render_value = True
        form.fields['password2'].widget.render_value = True
        form.fields['is_superuser'].widget.render_value = True
        form.fields['is_staff'].widget.render_value = True

        staffs = User.objects.filter(is_superuser=True).filter(is_staff=True)

        return render(request, template_name='accounts/admin-register-staff-account.html', context={'form': form, 'staffs': staffs})

    @method_decorator(login_required(login_url='/'))
    @method_decorator(admin_only())
    def post(self, request, *args, **kwargs):
        form = CreateSuperUserForm(request.POST)
        if form.is_valid():
            user = form.save()

            profile = Profile(user=user)
            profile.save()

            messages.add_message(request,
                                 messages.SUCCESS,
                                 'The administrator account was registered successfully.')
            return redirect("/administrator/staff")
        else:
            messages.add_message(request,
                                 messages.ERROR,
                                 'There was an error in creating the account.')
        return redirect("/administrator/staff")


@login_required(login_url='/')
@admin_only()
def deleteStaff(request, staff_id):
    if request.method == "POST":
        user = User.objects.filter(id=staff_id)
        user.delete()

        messages.add_message(request,
                             messages.SUCCESS,
                             'The administrator account was deleted successfully.')
        return redirect('/administrator/staff')

    return redirect('/administrator/staff')

accounts/templates/accounts/base.html
{% load static %}
<!-- Initiate loading of static files -->
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{% block title %}{% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}" />
  <!-- Import the created CSS file -->
</head>

<body>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  <footer class="page-footer p-2 " style="z-index: 0; bottom: 0;">
    <div class="footer-copyright py-2 text-center text-muted" style="font-size: 14px;">© 2021 EVEREST Developed by the EVEREST team | Jose Paulo C. Cabral | Joshua Albert T. Lopez | Reinhold E. Lucana | John Edward Sam T. Matienzo | All rights reserved.
    </div>
  </footer>
</body>

</html>

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block title %}
EVEREST | Login
{% endblock %}

{% block content %}
<div>
  <div class="container">
    
    <div class="mt-5" style="text-align: center;">
      <h1 class="brand">EVEREST</h1>
      <p><b>EVE</b>NT <b>RE</b>GISTRATION SY<b>ST</b>EM</p>
      <h6>FOR BRGY. TAÑONG, MARIKINA CITY SK</h6>
    </div>

    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h3 class="text-center">Sign In</h3>
            <br />
            <form class="form-signin" method="POST">
              {% csrf_token %}
              <div class="form-label-group">
                <input type="text" id="username" class="form-control" name="username" placeholder="Username" required autofocus />
                <label for="username">Username</label>
              </div>
          
              <div class="form-label-group">
                <input type="password" minlength="8" id="password" class="form-control" name="password" placeholder="Password"
                  required />
                <label for="password">Password</label>
              </div>
              <br />
              <button class="btn text-uppercase" type="submit" style="width: 100%;">
                Sign in
              </button>
              <hr class="my-4" />
          
              {% for message in messages %}
              <div class="alert alert-danger">
                <b class="text-center">{{ message }}</b>
              </div>
              {% endfor %}

              <p class="text-center">
                <a href="{% url 'reset_password' %}" style="text-decoration: none;">Forgot your password?</a>
              </p>
              
              <p class="text-center">
                Don't have an account yet?
                <a href="{% url 'register' %}" style="text-decoration: none;">Sign Up</a>
              </p>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/profile-admin.html
{% extends 'administrator/base.html' %}
{% load static %}

{% block title %}
EVEREST | {{ request.user.username }}'s Profile
{% endblock %}

{% block content %}
<style>
  .nounderline {
    color: rgb(105, 199, 236);
    text-decoration: none;
  }

  .nounderline:hover {
    color: rgb(117, 235, 235);
    text-decoration: underline;
  }

  .signin {
    display: block;
  }

  .updateprofile {
    background-color: rgb(46, 118, 136) !important;
  }

  .updateprofile:hover {
    background-color: rgb(60, 135, 206) !important;
  }

  @media (max-width:480px) {
    .signin {
      margin: 0;
      display: flex;
      justify-content: center;
      width: 100%;
    }
  }
</style>

<main>
  {% for message in messages %}
  {% if form.errors %}
  {% for field in form %}
  {% for error in field.errors %}
  <div class="alert alert-danger alert-dismissible"
    style="z-index: 2; background-color: #C0392B; position: absolute; margin-left: 2em; right: 2em; top: 8em;">
    <strong>{{ error|escape }}</strong>
    <button type="button" class="close btn btn-interact text-white" data-dismiss="alert"
      style="position: absolute; top:0; right: -2.7em;"><i class="far fa-times-circle fa-1x text-white"></i></button>
  </div>
  {% endfor %}
  {% endfor %}
  {% endif %}
  {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
  <p class="alert alert-danger alert-link alert-dismissible text-white"
    style="z-index: 2; background-color: #C0392B; position: absolute; margin-left: 2em; right: 2em; top: 8em;">
    {{ message }}
    <button type="button" class="close btn btn-interact" data-dismiss="alert"
      style="position: absolute; top:0; right: -2.7em;"><i class="far fa-times-circle fa-1x text-white"></i></button>
  </p>
  {% else %}
  <p class="alert alert-success alert-link alert-dismissible text-white"
    style="z-index: 2; background-color: #27AE60; position: absolute; margin-left: 2em; right: 2em; top: 8em;">
    {{message}}
    <button type="button" class="close btn btn-interact" data-dismiss="alert"
      style="position: absolute; top:0; right: -2.7em;"><i class="far fa-times-circle fa-1x text-white"></i></button>
  </p>
  {% endif %}
  {% endfor %}

  <div class="container">
    <div class="row">
      <div class="col-lg-5">
        <div class="card card-signin my-3">
          <div class="card-body">
            <h3 class="text-center">{{ request.user.first_name }} {{ request.user.last_name }}</h3>
            <div class="text-muted text-center" style="text-align: center;">{{ user.username }}</div>
            <br>

            <div class="form-signin">
              <div class="form-label-group">
                <div class="row">
                  <img class="profile-pic"
                    src="{% if request.user.profile.profile_pic %}{{ request.user.profile.profile_pic.url }}{% else %}{% static 'img/default-profile-icon.jpg' %}{% endif %}" />
                </div>
              </div>
              <a class="btn text-uppercase text-white" href="/"
                style="width: 100%; font-weight: bold; border-radius: 0.5em;"><i class="fa fa-home fa-3"
                  aria-hidden="true"></i> Go Back to Home</a>
            </div>

          </div>
        </div>
      </div>

      <div class="col-lg-7">
        <div class="card card-signin my-3">
          <div class="card-body">
            <h3 class="text-center">Profile Information</h3>
            <div>
              <p class="text-muted" style="text-align: center;">Account was created on: <span
                  style="text-transform: uppercase;">{{ request.user.date_joined }}</span>
              </p>
            </div>
            <hr>
            <br>

            <form class="form-signin" method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="form-label-group">
                <div class="row">
                  <div class="col form-label-group">
                    <input type="text" name="first_name" value="{{ request.user.first_name }}" maxlength="200"
                      class="form-control" placeholder="First Name" required="" id="id_first_name">
                    <label for="id_first_name">First Name</label>
                  </div>
                  <div class="col form-label-group">
                    <input type="text" name="last_name" value="{{ request.user.last_name }}" maxlength="200"
                      class="form-control" placeholder="Last Name" required="" id="id_last_name">
                    <label for="id_last_name">Last Name</label>
                  </div>
                </div>

                <div class="row">
                  <div class="form-label-group">
                    {{ form.affiliation }}
                    <label for="id_affiliation">Affiliation</label>
                  </div>
                </div>

                <div class="row">
                  <div class="form-label-group">
                    <input type="text" name="email" value="{{ request.user.email }}" maxlength="200"
                      class="form-control" placeholder="Email" required="" id="id_email">
                    <label for="id_email">Email</label>
                  </div>
                </div>

                <div class="row">
                  <div class="form-label-group">
                    <input type="text" name="username" value="{{ request.user.username }}" maxlength="200"
                      class="form-control" placeholder="username" required="" id="id_username">
                    <label for="id_username">Username</label>
                  </div>
                </div>

                <div class="row">
                  <div class="form-label-group">
                    <hr>
                    <br>
                    {% for i in form.profile_pic %}
                    <div class="mb-2">
                      {{ i }}
                    </div>
                    {% endfor %}
                  </div>
                </div>

                <hr class="my-3">

                <button type="submit" class="btn text-white text-uppercase updateprofile my-3" style="width: 100%;">SAVE
                  PROFILE</button>

            </form>

          </div>
        </div>
      </div>

    </div>
  </div>

</div>

<script>
  const profile_pic = document.querySelector('input[name="profile_pic"');
  profile_pic.classList.add('form-control-file');
</script>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'member/base.html' %}
{% load static %}

{% block title %}
EVEREST | {{ request.user.username }}'s Profile
{% endblock %}

{% block content %}
  <style>
    .nounderline {
      color: rgb(105, 199, 236);
      text-decoration: none;
    }
  
    .nounderline:hover {
      color: rgb(117, 235, 235);
      text-decoration: underline;
    }
  
    .signin {
      display: block;
    }
  
    .updateprofile {
      background-color: rgb(46, 118, 136) !important;
    }
  
    .updateprofile:hover {
      background-color: rgb(60, 135, 206) !important;
    }
  
    @media (max-width:480px) {
      .signin {
        margin: 0;
        display: flex;
        justify-content: center;
        width: 100%;
      }
    }
  </style>
  
  <main>
    {% for message in messages %}
    {% if form.errors %}
    {% for field in form %}
    {% for error in field.errors %}
    <div class="alert alert-danger alert-dismissible"
      style="z-index: 2; background-color: #C0392B; position: absolute; margin-left: 2em; right: 2em; top: 8em;">
      <strong>{{ error|escape }}</strong>
      <button type="button" class="close btn btn-interact text-white" data-dismiss="alert"
        style="position: absolute; top:0; right: -2.7em;"><i class="far fa-times-circle fa-1x text-white"></i></button>
    </div>
    {% endfor %}
    {% endfor %}
    {% endif %}
    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
    <p class="alert alert-danger alert-link alert-dismissible text-white"
      style="z-index: 2; background-color: #C0392B; position: absolute; margin-left: 2em; right: 2em; top: 8em;">
      {{ message }}
      <button type="button" class="close btn btn-interact" data-dismiss="alert"
        style="position: absolute; top:0; right: -2.7em;"><i class="far fa-times-circle fa-1x text-white"></i></button>
    </p>
    {% else %}
    <p class="alert alert-success alert-link alert-dismissible text-white"
      style="z-index: 2; background-color: #27AE60; position: absolute; margin-left: 2em; right: 2em; top: 8em;">
      {{message}}
      <button type="button" class="close btn btn-interact" data-dismiss="alert"
        style="position: absolute; top:0; right: -2.7em;"><i class="far fa-times-circle fa-1x text-white"></i></button>
    </p>
    {% endif %}
    {% endfor %}
    
    <div class="container">
      <div class="row">
        <div class="col-lg-5">
          <div class="card card-signin my-3">
            <div class="card-body">
              <h3 class="text-center">{{ request.user.first_name }} {{ request.user.last_name }}</h3>
              <div class="text-muted text-center" style="text-align: center;">{{ user.username }}</div>
              <br>
  
              <div class="form-signin">
                <div class="form-label-group">
                  <div class="row">
                    <img class="profile-pic"
                      src="{% if request.user.profile.profile_pic %}{{ request.user.profile.profile_pic.url }}{% else %}{% static 'img/default-profile-icon.jpg' %}{% endif %}" />
                  </div>
                </div>
                <a class="btn text-uppercase text-white" href="/"
                  style="width: 100%; font-weight: bold; border-radius: 0.5em;"><i class="fa fa-home fa-3"
                    aria-hidden="true"></i> Go Back to Home</a>
              </div>
  
            </div>
          </div>
        </div>
  
        <div class="col-lg-7">
          <div class="card card-signin my-3">
            <div class="card-body">
              <h3 class="text-center">Profile Information</h3>
              <div>
                <p class="text-muted" style="text-align: center;">Account was created on: <span style="text-transform: uppercase;">{{ request.user.date_joined }}</span>
                </p>
              </div>
              <hr>
              <br>
  
              <form class="form-signin" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-label-group">
                  <div class="row">
                    <div class="col form-label-group">
                      <input type="text" name="first_name" value="{{ request.user.first_name }}" maxlength="200" class="form-control" placeholder="First Name"
                        required="" id="id_first_name">
                      <label for="id_first_name">First Name</label>
                    </div>
                    <div class="col form-label-group">
                      <input type="text" name="last_name" value="{{ request.user.last_name }}" maxlength="200" class="form-control" placeholder="Last Name"
                        required="" id="id_last_name">
                      <label for="id_last_name">Last Name</label>
                    </div>
                  </div>

                  <div class="row">
                    <div class="form-label-group">
                        {{ form.affiliation }}
                      <label for="id_affiliation">Affiliation</label>
                    </div>
                  </div>
  
                  <div class="row">
                    <div class="form-label-group">
                      <input type="text" name="email" value="{{ request.user.email }}" maxlength="200" class="form-control" placeholder="Email"
                        required="" id="id_email">
                      <label for="id_email">Email</label>
                    </div>
                  </div>
  
                  <div class="row">
                    <div class="form-label-group">
                      <input type="text" name="username" value="{{ request.user.username }}" maxlength="200" class="form-control" placeholder="username"
                        required="" id="id_username">
                      <label for="id_username">Username</label>
                    </div>
                  </div>
  
                  <div class="row">
                    <div class="form-label-group">
                      <hr>
                      <br>
                      {% for i in form.profile_pic %}
                      <div class="mb-2">
                        {{ i }}
                      </div>
                      {% endfor %}
                    </div>
                  </div>
  
                  <hr class="my-3">
  
                  <button type="submit" class="btn text-white text-uppercase updateprofile my-3" style="width: 100%;">SAVE PROFILE</button>
  
              </form>
  
            </div>
          </div>
        </div>
  
      </div>
    </div>
  
  </div>
  
  <script>
    const profile_pic = document.querySelector('input[name="profile_pic"');
    profile_pic.classList.add('form-control-file');
  </script>
{% endblock %}

accounts/templates/accounts/registration-success.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block title %}
EVEREST | Registration Successful
{% endblock %}

{% block content %}
<div>
  <div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h3 class="text-center">Registration Successful!</h3>
            <br />

            <p class="text-center">
              You have successfully registered an account. You may now
              proceed on logging in.
            </p>

            <a name="Create User" class="btn text-uppercase text-white bg-info" href="{% url 'login' %}"
              style="width: 100%;"><b>LOGIN</b></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}