administrator/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('dashboard', views.AdministratorDashboard.as_view(),
         name='administrator-dashboard'),
    path('events/create-new', views.CreateEvent.as_view(),
         name='create-event'),
    path('events/list', views.ListEvents.as_view(),
         name='list-events'),
    path('events/update/<int:event_id>/',
         views.UpdateEvent.as_view(), name='update-event'),
    path('events/delete/<int:event_id>', views.deleteEvent, name='delete-event'),
    path('members/list', views.ListMembers.as_view(),
         name='list-members'),
    path('members/delete/<int:member_id>',
         views.deleteMember, name='delete-member'),
    path('transactions', views.AllTransactions.as_view(), name='all-transactions'),
    path('transactions/transaction/set-status/<int:transaction_id>',
         views.SetTransactionStatus.as_view(), name='set-transaction-status'),
    path('events/event/<int:event_id>/reports',
         views.EventReports.as_view(), name='event-reports'),
    path('members/member/<int:member_id>/profile',
         views.MemberProfile.as_view(), name='member-profile'),
    path('support-contacts', views.SupportContacts.as_view(),
         name='list-members'),
    path('support-contact/delete/<int:contact_id>',
         views.deleteContact, name='delete-contact'),
    path('announcements', views.Announcement.as_view(),
         name='announcement'),
]

event_registration_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('administrator/', include('administrator.urls')),
    path('member/', include('member.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

member/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static

urlpatterns = [
    path('dashboard', views.MemberDashboard.as_view(),
         name='member-dashboard'),
    path('events/find', views.FindEvent.as_view(),
         name='find-event'),
    path('events/event/<int:event_id>', views.ViewEvent.as_view(),
         name='view-event'),
    path('events/event/register/<int:event_id>',
         views.registerEvent, name='register-event'),
    path('events/event/unregister/<int:event_id>',
         views.unregisterEvent, name='unregister-event'),
    path('events/event/confirm-attendance/<int:event_id>',
         views.confirmAttendance, name='confirm-attendance'),
    path('events/event/register/form/<int:event_id>', views.PaidRegistration.as_view(),
         name='paid-registration'),
    path('events/joined', views.EventsJoined.as_view(),
         name='find-event'),
    path('transactions', views.Transactions.as_view(),
         name='transactions'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    profile_pic = models.ImageField(null=True, blank=True)
    affiliation = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.user.username

administrator/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.


class Event(models.Model):
    EVENT_TYPE = (
        ('CONFERENCE', 'CONFERENCE'),
        ('SEMINAR', 'SEMINAR'),
        ('WORKSHOP', 'WORKSHOP'),
    )

    EVENT_COST = (
        ('FREE', 'FREE'),
        ('PAID', 'PAID'),
    )

    event_name = models.CharField(max_length=200, null=True)
    short_description = models.CharField(max_length=200, null=True)
    detailed_description = RichTextField(blank=True, null=True)
    event_type = models.CharField(
        max_length=200, null=True, choices=EVENT_TYPE)
    date = models.DateTimeField(auto_now_add=False, null=True)
    location = models.CharField(max_length=200, null=True)
    is_registration_open = models.BooleanField(null=False)
    is_attendance_open = models.BooleanField(null=False)
    cost = models.CharField(
        max_length=200, null=True, choices=EVENT_COST)
    price = models.DecimalField(max_digits=19, decimal_places=2)

    def __str__(self):
        return self.event_name


class SupportContact(models.Model):
    CONTACT_TYPE = (
        ('EMAIL', 'EMAIL'),
        ('NUMBER', 'NUMBER'),
    )

    support_contact = models.CharField(max_length=200, null=True)
    contact_type = models.CharField(
        max_length=200, null=True, choices=CONTACT_TYPE)

    def __str__(self):
        return self.support_contact


class Banner(models.Model):
    POSITION = (
        ('1ST BANNER', '1ST BANNER'),
        ('2ND BANNER', '2ND BANNER'),
        ('3RD BANNER', '3RD BANNER'),
    )

    position = models.CharField(
        max_length=200, null=True, choices=POSITION)
    banner_img = models.ImageField(null=True)
    date_added = models.DateTimeField(auto_now_add=True, null=True)

administrator/forms.py
from django.forms import ModelForm
from django import forms
from .models import *
from bootstrap_datepicker_plus import DateTimePickerInput


class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = '__all__'
        widgets = {
            'date': DateTimePickerInput
        }

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)

        self.fields['event_name'].widget.attrs.update(
            {'class': 'form-control', 'required': 'required', 'autofocus': 'autofocus'})
        self.fields['short_description'].widget.attrs.update(
            {'class': 'form-control', })
        self.fields['location'].widget.attrs.update(
            {'class': 'form-control', })
        self.fields['detailed_description'].widget.attrs.update(
            {'class': 'form-control django-ckeditor-widget', })
        self.fields['event_type'].widget.attrs.update(
            {'class': 'form-control', })
        self.fields['date'].widget.attrs.update(
            {'class': 'form-control datetimepicker-input', 'data-target': '#datetimepicker1'})
        self.fields['is_attendance_open'].widget.attrs.update(
            {'class': '', })
        self.fields['is_registration_open'].widget.attrs.update(
            {'class': '', })
        self.fields['cost'].widget.attrs.update(
            {'class': 'form-control', 'onchange': 'displayDivDemo(this)'})
        self.fields['price'].widget.attrs.update(
            {'class': 'form-control', })


class ContactForm(ModelForm):
    class Meta:
        model = SupportContact
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)

        self.fields['contact_type'].widget.attrs.update(
            {'class': 'form-control', 'required': 'required'})
        self.fields['support_contact'].widget.attrs.update(
            {'class': 'form-control', 'required': 'required'})


class BannerForm(ModelForm):
    class Meta:
        model = Banner
        fields = '__all__'
        exclude = ['date_added']

    def __init__(self, *args, **kwargs):
        super(BannerForm, self).__init__(*args, **kwargs)

        self.fields['position'].widget.attrs.update(
            {'class': 'form-control', 'required': 'required'})
        self.fields['banner_img'].widget.attrs.update(
            {'class': 'form-control', 'required': 'required'})

administrator/views.py
from member.views import Transactions
from member.forms import EventRegistrationForm
from django.core.exceptions import EmptyResultSet
from django.shortcuts import render, redirect
from django.views import View
from django.http import HttpResponse
from .decorators import *
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .forms import *
from django.contrib import messages
from accounts.models import Profile, User
from django.db.models import Q
from member.models import Event, EventRegistration
from member.filters import FindEventFilter, EventsJoinedFilter
import datetime
from datetime import timedelta

# Create your views here.


class AdministratorDashboard(View):
    @method_decorator(login_required(login_url='/'))
    @method_decorator(admin_only())
    def get(self, request, *args, **kwargs):
        approved = EventRegistration.objects.filter(
            is_registration_approved='APPROVED').count()
        pending = EventRegistration.objects.filter(
            is_registration_approved='PENDING').count()
        rejected = EventRegistration.objects.filter(
            is_registration_approved='REJECTED').count()
        recent = EventRegistration.objects.order_by('-date_created')[:20]

        today_min = datetime.datetime.combine(
            datetime.date.today(), datetime.time.min)
        today_max = datetime.datetime.combine(
            datetime.date.today(), datetime.time.max)
        today = Event.objects.filter(
            date__range=(today_min, today_max))

        this_day = datetime.datetime.today()
        upcoming = Event.objects.filter(
            date__gte=this_day).order_by('date')

        previous = Event.objects.filter(date__lte=this_day).exclude(
            date__range=(today_min, today_max)).order_by('-date')[:5]

        event_objs = Event.objects.order_by('-date')[:10]

        events = []
        registered = []
        attended = []

        for i in event_objs:
            events.append(i.event_name)

            user_confirmed_attendance = EventRegistration.objects.filter(
                event=i).filter(
                is_registration_approved='APPROVED').count()
            registered.append(user_confirmed_attendance)

            user_confirmed_attendance = EventRegistration.objects.filter(event=i).exclude(
                time_of_attendance__isnull=True).count()
            attended.append(user_confirmed_attendance)
        return render(request, template_name='administrator/dashboard.html', context={'approved': approved, 'pending': pending, 'rejected': rejected, 'recent': recent, 'today': today, 'upcoming': upcoming, 'previous': previous, 'events': events, 'registered': registered, 'attended': attended})


class CreateEvent(View):
    @method_decorator(login_required(login_url='/'))
    @method_decorator(admin_only())
    def get(self, request, *args, **kwargs):
        form = EventForm()
        return render(request, template_name='administrator/event-form.html', context={'form': form})

    @method_decorator(login_required(login_url='/'))
    @method_decorator(admin_only())
    def post(self, request, *args, **kwargs):
        form = EventForm(request.POST)
        if form.is_valid():
            form.save()

            messages.add_message(request,
                                 messages.SUCCESS,
                                 'The event was added successfully.')
            return redirect('/administrator/events/list')
        else:
            messages.error(request, 'The event was not added due to an error.')
            return render(request, template_name='administrator/event-form.html', context={'form': form})


class UpdateEvent(View):
    @method_decorator(login_required(login_url='/'))
    @method_decorator(admin_only())
    def get(self, request, *args, **kwargs):
        event_id = self.kwargs['event_id']
        event = Event.objects.get(pk=event_id)

        form = EventForm(instance=event)
        return render(request, template_name='administrator/event-form.html', context={'form': form})

    @method_decorator(login_required(login_url='/'))
    @method_decorator(admin_only())
    def post(self, request, *args, **kwargs):
        event_id = self.kwargs['event_id']
        event = Event.objects.get(pk=event_id)

        form = EventForm(request.POST, instance=event)
        if form.is_valid():
            form.save()

            messages.add_message(request,
                                 messages.SUCCESS,
                                 'The event was updated successfully.')
            return redirect('/administrator/events/event/{}/reports'.format(event_id))
        else:
            messages.error(
                request, 'The event was not updated due to an error.')
            return render(request, template_name='administrator/event-form.html', context={'form': form})


class ListEvents(View):
    @method_decorator(login_required(login_url='/'))
    @method_decorator(admin_only())
    def get(self, request, *args, **kwargs):
        events = Event.objects.all().order_by('-date')

        find_event_filter = FindEventFilter(request.GET, queryset=events)
        events = find_event_filter.qs

        return render(request, template_name='administrator/list-events.html', context={'events': events, 'find_event_filter': find_event_filter})


@login_required(login_url='/')
@admin_only()
def deleteEvent(request, event_id):
    if request.method == "POST":
        event = Event.objects.filter(id=event_id)
        event.delete()

        messages.add_message(request,
                             messages.SUCCESS,
                             'The event was deleted successfully.')
        return redirect('/administrator/events/list')

    return redirect('/administrator/events/list')


class ListMembers(View):
    @method_decorator(login_required(login_url='/'))
    @method_decorator(admin_only())
    def get(self, request, *args, **kwargs):
        registered_events = EventRegistration.objects.exclude(
            time_of_attendance__isnull=True)

        members = User.objects.exclude(
            Q(is_superuser=True)).order_by('first_name')
        return render(request, template_name='administrator/list-members.html', context={'members': members, 'registered_events': registered_events})


@login_required(login_url='/')
@admin_only()
def deleteMember(request, member_id):
    if request.method == "POST":
        user = User.objects.filter(id=member_id)
        user.delete()

        messages.add_message(request,
                             messages.SUCCESS,
                             'The user was deleted successfully.')
        return redirect('/administrator/members/list')

    return redirect('/administrator/members/list')


class AllTransactions(View):
    @method_decorator(login_required(login_url='/'))
    def get(self, request, *args, **kwargs):
        transactions = EventRegistration.objects.all().order_by('-date_created')

        transactions_filter = EventsJoinedFilter(
            request.GET, queryset=transactions)
        transactions = transactions_filter.qs

        return render(request, template_name='administrator/transactions.html', context={'transactions': transactions, 'transactions_filter': transactions_filter})


class SetTransactionStatus(View):
    @method_decorator(login_required(login_url='/'))
    def get(self, request, *args, **kwargs):
        transaction_id = self.kwargs['transaction_id']
        transaction = EventRegistration.objects.get(pk=transaction_id)

        form = EventRegistrationForm(instance=transaction)

        return render(request, template_name='administrator/set-transaction-status.html', context={'transaction': transaction, 'form': form})

    @method_decorator(login_required(login_url='/'))
    def post(self, request, *args, **kwargs):
        transaction_id = self.kwargs['transaction_id']
        transaction = EventRegistration.objects.get(pk=transaction_id)

        form = EventRegistrationForm(
            request.POST, request.FILES, instance=transaction)
        if form.is_valid():
            form.save()

            messages.add_message(request,
                                 messages.SUCCESS,
                                 'Transaction ID: {} was updated successfully.'.format(transaction_id))
            return redirect('/administrator/transactions')
        else:
            messages.error(
                request, 'Transaction ID: {} was not updated due to an error.'.format(transaction_id))
            return redirect('/administrator/transactions')


class EventReports(View):
    @method_decorator(login_required(login_url='/'))
    def get(self, request, *args, **kwargs):
        event_id = self.kwargs['event_id']
        event = Event.objects.get(pk=event_id)

        user_registered_events = EventRegistration.objects.filter(event=event)

        user_registered_events_approved = EventRegistration.objects.filter(
            is_registration_approved='APPROVED')
        user_registered_events_pending = EventRegistration.objects.filter(
            is_registration_approved='PENDING')
        user_registered_events_rejected = EventRegistration.objects.filter(
            is_registration_approved='REJECTED')

        user_confirmed_attendance = EventRegistration.objects.filter(event=event).exclude(
            time_of_attendance__isnull=True).values_list('event_id', flat=True)

        transactions_filter = EventsJoinedFilter(
            request.GET, queryset=user_registered_events)
        user_registered_events = transactions_filter.qs

        registered = user_registered_events_approved.filter(event=event).filter(
            is_registration_approved='APPROVED').count()

        attended = user_registered_events_approved.filter(event=event).filter(
            is_registration_approved='APPROVED').exclude(
            time_of_attendance__isnull=True).count()

administrator/templates/administrator/event-form.html
{% extends 'administrator/base.html' %}
{% load static %}

{% block title %}
EVEREST | Event
{% endblock %}

{% block content %}
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"> -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<style>
.switch {
  position: relative;
  display: inline-block;
  width: 3em;
  height: 1.5em;
}

.switch input { 
  opacity: 0;
  width: 0;
  height: 0;
}

.slider {
  position: absolute;
  cursor: pointer;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: #ccc;
  -webkit-transition: .4s;
  transition: .4s;
}

.slider:before {
  position: absolute;
  content: "";
  height: 1.1em;
  width: 1.1em;
  left: 0.3em;
  bottom: 0.2em;
  background-color: white;
  -webkit-transition: .4s;
  transition: .4s;
}

input:checked + .slider {
  background-color: #2196F3;
}

input:focus + .slider {
  box-shadow: 0 0 1px #2196F3;
}

input:checked + .slider:before {
  -webkit-transform: translateX(1.3em);
  -ms-transform: translateX(1.3em);
  transform: translateX(1.3em);
}

/* Rounded sliders */
.slider.round {
  border-radius: 34px;
}

.slider.round:before {
  border-radius: 50%;
}
</style>

<main class="">
  

  <form method="POST">
    {% csrf_token %}

    {{ form.media }}

    <div class="form-group row" style="margin-left: 2em;">
      <div class="form-group row">
        <div class="col-md-8" style="margin-top:0.5rem; margin-bottom:0.5rem;">
          <label for="id_event_name">Event Name</label>
          {{ form.event_name }}
        </div>

        <div class="col-md-2 text-center align-items-center my-4" style="margin-top:0.5rem; margin-bottom:0.5rem;">
          <div class="form-control">
            <label for="id_is_registration_open">Registration</label>
            <br>

            <label class="switch">
              {{ form.is_registration_open }}
              <span class="slider round"></span>
            </label>
          </div>
        </div>

        <div class="col-md-2 text-center align-items-center my-4" style="margin-top:0.5rem; margin-bottom:0.5rem;">
          <div class="form-control">
            <label for="id_is_attendance_open">Attendance</label>
            <br>
        
            <label class="switch">
              {{ form.is_attendance_open }}
              <span class="slider round"></span>
            </label>
          </div>
        </div>
        
      </div>
      
      <div class="form-group row">
        <div class="col-md-12" style="margin-top:0.5rem; margin-bottom:0.5rem;">
          <label for="id_short_description">Short Description</label>
          {{ form.short_description }}
        </div>
      </div>
      
      <div class="form-group row">
        <div class="col text-center" style="margin-top:0.5rem; margin-bottom:0.5rem;">
          <label for="id_detailed_description">Detailed Description</label>
          <br>
          {{ form.detailed_description }}
        </div>
      </div>
      

      <div class="form-group row text-center">
        <style>
            .input-group-text {
              padding-bottom: 1em !important;
              align-items: center !important;
            }
        </style>

        <div class="form-group row">
          <div class="col-md-6" style="margin-top:0.5rem; margin-bottom:0.5rem;" style="align-items: center;">
            <label for="id_event_type">Event Type</label>
            {{ form.event_type }}
          </div>
          <div class="col-md-6" style="margin-top:0.5rem; margin-bottom:0.5rem;">
            <label for="id_date">Date and Time</label>
            {{ form.date }}
          </div>
        </div>

        <div class="form-group row">
          <div class="col-md-12" style="margin-top:0.5rem; margin-bottom:0.5rem;">
            <label for="id_location">Location</label>
            {{ form.location }}
          </div>
        </div>
        
        <div class="form-group row">
          <div class="col-md-6" style="margin-top:0.5rem; margin-bottom:0.5rem;">
            <label for="id_cost">Price Type</label>
            {{ form.cost }}
          </div>
        
          <style>
            #hideValuesOnSelect {
              display: block;
            }
          </style>
        
          <div class="col-md-6" id="hideValuesOnSelect" style="margin-top:0.5rem; margin-bottom:0.5rem;">
            <label for="id_price">Price</label>
            {{ form.price }}
          </div>
        
          <script>
            function displayDivDemo(elementValue) {
              if (elementValue.value == 'FREE') {
                document.getElementById('hideValuesOnSelect').style.display = 'none';
                document.getElementById('id_price').value = 0;
              }
              else {
                document.getElementById('hideValuesOnSelect').style.display = 'block';
              }
            }
          </script>
        </div>
      </div>

      <div class="form-group row my-3">
        <div class="col-md-12"></div>
          <button type="submit" class="btn btn-primary form-control" style="font-weight: 800;">SAVE</button>
        </div>
      </div>

    </div>

  </form>
</main>


{% endblock %}

administrator/templates/administrator/list-events.html
{% extends 'administrator/base.html' %}
{% load static %}

{% block title %}
EVEREST | List of Events
{% endblock %}

{% block content %}
<main class="container-fluid">

  <h1 class="text-center" style="font-weight: bold;">LIST OF EVENTS</h1>
  <hr class="my-4">

  {% for message in messages %}
    {% if form.errors %}
      {% for field in form %}
        {% for error in field.errors %}
          <div class="alert alert-danger alert-dismissible" style="z-index: 2; background-color: #C0392B; position: absolute; margin-left: 2em; right: 2em; top: 8em;">
            <strong>{{ error|escape }}</strong>
            <button type="button" class="close btn btn-interact text-white" data-dismiss="alert" style="position: absolute; top:0; right: -2.7em;"><i class="far fa-times-circle fa-1x text-white"></i></button>
          </div>
        {% endfor %}
      {% endfor %}
    {% endif %}
    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
      <p class="alert alert-danger alert-link alert-dismissible text-white" style="z-index: 2; background-color: #C0392B; position: absolute; margin-left: 2em; right: 2em; top: 8em;">
        {{ message }}
        <button type="button" class="close btn btn-interact" data-dismiss="alert" style="position: absolute; top:0; right: -2.7em;"><i class="far fa-times-circle fa-1x text-white"></i></button>
      </p>
    {% else %}
      <p class="alert alert-success alert-link alert-dismissible text-white" style="z-index: 2; background-color: #27AE60; position: absolute; margin-left: 2em; right: 2em; top: 8em;">
        {{message}}
        <button type="button" class="close btn btn-interact" data-dismiss="alert" style="position: absolute; top:0; right: -2.7em;"><i class="far fa-times-circle fa-1x text-white"></i></button>
      </p>
    {% endif %}
  {% endfor %}
  
  <form method="GET" class="form-control container-fluid mb-3 p-3" style="border: none;">
    <div class="container-fluid row" style="align-items: center; text-align: center;">
      <div class="form-group col-md-4">
        <label for="id_name">Keyword: </label>
        {{ find_event_filter.form.search_fields }}
      </div>
  
      <div class="form-group col-md-2">
        <label for="id_cost">Price: </label>
        {{ find_event_filter.form.cost }}
      </div>
  
      <div class="form-group col-md-3">
        <label for="id_event_type">Type: </label>
        {{ find_event_filter.form.event_type }}
      </div>
  
      <div class="form-group col container">
        <button class="btn btn-secondary"
          style="font-weight: bold; background-color: rgba(34, 166, 170, 0.918); border: none;"
          type="submit">SEARCH</button>
      </div>
    </div>
  </form>
  
  <div>
    <table id="qlist" style="width: 100%;">
      <thead>
        <th>
          ID
        </th>
        <th>
          EVENT
        </th>
        <th>
          DATE
        </th>
        <th>
          DESCRIPTION
        </th>
        <th></th>
        <th></th>
        <th></th>
      </thead>
  
      {% for event in events %}
      <tr>
        <td>{{ event.id }}</td>
        <td>{{ event.event_name }}</td>
        <td>{{ event.date }}</td>
        <td>{{ event.short_description }}</td>
        <td>
          <a class="btn btn-interact btn-primary" href="/administrator/events/event/{{ event.id }}/reports">Reports</a>
        </td>
        <td>
          <a class="btn btn-interact btn-warning" href="/administrator/events/update/{{event.id}}"><span
              style="color:white;">Update</span></a>
        </td>
        <td>
          <form onsubmit="return confirm('WARNING: Deleting an item is irreversible. Are you sure you want to delete the event: {{ event.id }} - {{ event.event_name }}?');" method="POST" action="{% url 'delete-event' event.id  %}">{% csrf_token %}
            <button type="submit" class="btn btn-interact btn-danger">Delete</button><input type="hidden" name="q_id"
              value="{{i.id}}" />
          </form>
        </td>
      </tr>
      {% endfor %}
  
    </table>
  </div>


</main>

<script>
  $(document).ready(function () {
    $('#qlist').DataTable({
      dom: 'Bfrltip',
      buttons: [
        {
          extend: 'csv',
          text: 'CSV',
          className: 'btn btn-default',
          exportOptions: {
            columns: 'th:not(:nth-last-child(-n + 3))'
          }
        },
        {
          extend: 'excel',
          text: 'Excel',
          className: 'btn btn-default',
          exportOptions: {
            columns: 'th:not(:nth-last-child(-n + 3))'
          }
        },
        {
          extend: 'pdf',
          text: 'PDF',
          className: 'btn btn-default',
          exportOptions: {
            columns: 'th:not(:nth-last-child(-n + 3))'
          }
        },
        {
          extend: 'print',
          text: 'Print',
          className: 'btn btn-default',
          exportOptions: {
            columns: 'th:not(:nth-last-child(-n + 3))'
          }
        },
      ],
      "lengthMenu": [[5, 10, 50, -1], [5, 10, 50, "All"]],
      "pagingType": "full_numbers",
      "pageLength": 10,
      "scrollX": true
    });
  });
</script>

{% endblock %}