event_registration_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('administrator/', include('administrator.urls')),
    path('member/', include('member.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

member/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static

urlpatterns = [
    path('dashboard', views.MemberDashboard.as_view(),
         name='member-dashboard'),
    path('events/find', views.FindEvent.as_view(),
         name='find-event'),
    path('events/event/<int:event_id>', views.ViewEvent.as_view(),
         name='view-event'),
    path('events/event/register/<int:event_id>',
         views.registerEvent, name='register-event'),
    path('events/event/unregister/<int:event_id>',
         views.unregisterEvent, name='unregister-event'),
    path('events/event/confirm-attendance/<int:event_id>',
         views.confirmAttendance, name='confirm-attendance'),
    path('events/event/register/form/<int:event_id>', views.PaidRegistration.as_view(),
         name='paid-registration'),
    path('events/joined', views.EventsJoined.as_view(),
         name='find-event'),
    path('transactions', views.Transactions.as_view(),
         name='transactions'),
]

administrator/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.


class Event(models.Model):
    EVENT_TYPE = (
        ('CONFERENCE', 'CONFERENCE'),
        ('SEMINAR', 'SEMINAR'),
        ('WORKSHOP', 'WORKSHOP'),
    )

    EVENT_COST = (
        ('FREE', 'FREE'),
        ('PAID', 'PAID'),
    )

    event_name = models.CharField(max_length=200, null=True)
    short_description = models.CharField(max_length=200, null=True)
    detailed_description = RichTextField(blank=True, null=True)
    event_type = models.CharField(
        max_length=200, null=True, choices=EVENT_TYPE)
    date = models.DateTimeField(auto_now_add=False, null=True)
    location = models.CharField(max_length=200, null=True)
    is_registration_open = models.BooleanField(null=False)
    is_attendance_open = models.BooleanField(null=False)
    cost = models.CharField(
        max_length=200, null=True, choices=EVENT_COST)
    price = models.DecimalField(max_digits=19, decimal_places=2)

    def __str__(self):
        return self.event_name


class SupportContact(models.Model):
    CONTACT_TYPE = (
        ('EMAIL', 'EMAIL'),
        ('NUMBER', 'NUMBER'),
    )

    support_contact = models.CharField(max_length=200, null=True)
    contact_type = models.CharField(
        max_length=200, null=True, choices=CONTACT_TYPE)

    def __str__(self):
        return self.support_contact


class Banner(models.Model):
    POSITION = (
        ('1ST BANNER', '1ST BANNER'),
        ('2ND BANNER', '2ND BANNER'),
        ('3RD BANNER', '3RD BANNER'),
    )

    position = models.CharField(
        max_length=200, null=True, choices=POSITION)
    banner_img = models.ImageField(null=True)
    date_added = models.DateTimeField(auto_now_add=True, null=True)

member/models.py
from administrator.models import Event
from django.db import models
from accounts.models import Profile
from administrator.models import Event

# Create your models here.


class EventRegistration(models.Model):

    APPROVAL = (
        ('APPROVED', 'APPROVED'),
        ('PENDING', 'PENDING'),
        ('REJECTED', 'REJECTED'),
    )

    user = models.ForeignKey(Profile, null=True, on_delete=models.CASCADE)
    receipt = models.ImageField(null=True, blank=True)
    event = models.ForeignKey(Event, null=True, on_delete=models.CASCADE)
    is_registration_approved = models.CharField(
        max_length=200, null=True, choices=APPROVAL)
    time_of_attendance = models.DateTimeField(
        auto_now_add=False, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.user.user.username + "+" + self.event.event_name

member/forms.py
from django.forms import ModelForm
from django import forms
from .models import *


class EventRegistrationForm(ModelForm):
    class Meta:
        model = EventRegistration
        fields = ['receipt', 'is_registration_approved']

    def __init__(self, *args, **kwargs):
        super(EventRegistrationForm, self).__init__(*args, **kwargs)

        self.fields['is_registration_approved'].widget.attrs.update(
            {'class': 'form-control', 'required': 'required'})
        self.fields['receipt'].widget.attrs.update(
            {'class': 'form-control upload-image-receipt'})

member/views.py
from django.db.models import query
from django.shortcuts import render, redirect
from django.views import View
from django.http import HttpResponse, HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from administrator.models import Event, SupportContact
from .models import *
from .filters import *
from django.contrib import messages
from django.utils import timezone
import datetime
from .forms import EventRegistrationForm
from member.models import Event, EventRegistration

# Create your views here.


class MemberDashboard(View):
    @method_decorator(login_required(login_url='/'))
    def get(self, request, *args, **kwargs):
        user = Profile.objects.get(id=request.user.profile.id)
        registered_events = EventRegistration.objects.filter(
            user=user).order_by("-date_created")[:10]

        approved = EventRegistration.objects.filter(user=user).filter(
            is_registration_approved='APPROVED').count()
        pending = EventRegistration.objects.filter(user=user).filter(
            is_registration_approved='PENDING').count()
        rejected = EventRegistration.objects.filter(user=user).filter(
            is_registration_approved='REJECTED').count()

        banner1 = Banner.objects.filter(
            position="1ST BANNER")
        if not banner1:
            banner1 = None
        else:
            banner1 = Banner.objects.filter(
                position="1ST BANNER").latest('date_added')

        banner2 = Banner.objects.filter(
            position="2ND BANNER")
        if not banner2:
            banner2 = None
        else:
            banner2 = Banner.objects.filter(
                position="2ND BANNER").latest('date_added')

        banner3 = Banner.objects.filter(
            position="3RD BANNER")
        if not banner3:
            banner3 = None
        else:
            banner3 = Banner.objects.filter(
                position="3RD BANNER").latest('date_added')
        return render(request, template_name='member/dashboard.html', context={'banner1': banner1, 'banner2': banner2, 'banner3': banner3, 'registered_events': registered_events, 'approved': approved, 'pending': pending, 'rejected': rejected})


class FindEvent(View):
    @method_decorator(login_required(login_url='/'))
    def get(self, request, *args, **kwargs):
        events = Event.objects.filter(
            is_registration_open=True).order_by('date')
        user = Profile.objects.get(id=request.user.profile.id)
        user_registered_events_approved = EventRegistration.objects.filter(
            user=user).filter(is_registration_approved='APPROVED').values_list('event_id', flat=True)
        user_registered_events_pending = EventRegistration.objects.filter(
            user=user).filter(is_registration_approved='PENDING').values_list('event_id', flat=True)
        user_registered_events_rejected = EventRegistration.objects.filter(
            user=user).filter(is_registration_approved='REJECTED').values_list('event_id', flat=True)

        find_event_filter = FindEventFilter(request.GET, queryset=events)
        events = find_event_filter.qs

        return render(request, template_name='member/find-event.html', context={'events': events, 'user_registered_events_approved': user_registered_events_approved, 'user_registered_events_pending': user_registered_events_pending, 'user_registered_events_rejected': user_registered_events_rejected, 'find_event_filter': find_event_filter})


class ViewEvent(View):
    @method_decorator(login_required(login_url='/'))
    def get(self, request, *args, **kwargs):
        event_id = self.kwargs['event_id']
        event = Event.objects.get(pk=event_id)
        user = Profile.objects.get(id=request.user.profile.id)

        support_contacts_email = SupportContact.objects.filter(
            contact_type='EMAIL').values_list('support_contact', flat=True)
        support_contacts_number = SupportContact.objects.filter(
            contact_type='NUMBER').values_list('support_contact', flat=True)

        user_registered_events_approved = EventRegistration.objects.filter(
            user=user).filter(is_registration_approved='APPROVED').values_list('event_id', flat=True)
        user_registered_events_pending = EventRegistration.objects.filter(
            user=user).filter(is_registration_approved='PENDING').values_list('event_id', flat=True)
        user_registered_events_rejected = EventRegistration.objects.filter(
            user=user).filter(is_registration_approved='REJECTED').values_list('event_id', flat=True)

        user_confirmed_attendance = EventRegistration.objects.filter(
            user=user).filter(event=event).exclude(time_of_attendance__isnull=True).values_list('event_id', flat=True)

        return render(request, template_name='member/event-details.html', context={'event': event, 'user_registered_events_approved': user_registered_events_approved, 'user_registered_events_pending': user_registered_events_pending, 'user_registered_events_rejected': user_registered_events_rejected, 'support_contacts_email': support_contacts_email, 'support_contacts_number': support_contacts_number, 'user_confirmed_attendance': user_confirmed_attendance})


@login_required(login_url='/')
def registerEvent(request, event_id):
    if request.method == "POST":
        user = Profile.objects.get(id=request.user.profile.id)
        event = Event.objects.get(id=event_id)
        time = timezone.now()

        if event.cost == "FREE":
            approval = 'APPROVED'
            new_event_registration = EventRegistration.objects.create(
                user=user, event=event, is_registration_approved=approval)

            messages.add_message(request,
                                 messages.SUCCESS,
                                 'You have successfully registered on the event.')
            return redirect("/member/events/event/{}".format(event_id))

        else:
            return redirect('/member/events/event/register/form/{}'.format(event_id))


@login_required(login_url='/')
def unregisterEvent(request, event_id):
    if request.method == "POST":
        user = Profile.objects.get(id=request.user.profile.id)
        event = Event.objects.get(id=event_id)

        event_registered = EventRegistration.objects.filter(
            user=user, event=event)

        event_registered.delete()
        messages.add_message(request,
                             messages.SUCCESS,
                             'You have successfully unregistered from the event.')
        return redirect("/member/events/event/{}".format(event_id))


@login_required(login_url='/')
def confirmAttendance(request, event_id):
    if request.method == "POST":
        user = Profile.objects.get(id=request.user.profile.id)
        event = Event.objects.get(id=event_id)

        event_registered = EventRegistration.objects.get(
            user=user, event=event)

        event_registered.time_of_attendance = timezone.now()
        event_registered.save()

        messages.add_message(request,
                             messages.SUCCESS,
                             'Yor attendance was recorded successfully.')
        return redirect("/member/events/event/{}".format(event_id))


class PaidRegistration(View):
    @method_decorator(login_required(login_url='/'))
    def get(self, request, *args, **kwargs):
        event_id = self.kwargs['event_id']
        event = Event.objects.get(pk=event_id)
        user = Profile.objects.get(id=request.user.profile.id)

        form = EventRegistrationForm()

        user_registered_event = EventRegistration.objects.filter(
            user=user).filter(event=event_id).values_list('event_id', flat=True)

        return render(request, template_name='member/paid-registration-form.html', context={'form': form, 'user_registered_event': user_registered_event, 'user': user, 'event': event})

    @method_decorator(login_required(login_url='/'))
    def post(self, request, *args, **kwargs):
        event_id = self.kwargs['event_id']
        event = Event.objects.get(pk=event_id)
        user = Profile.objects.get(id=request.user.profile.id)
        approval = "PENDING"

        receipt = request.FILES['receipt']

        event_reg = EventRegistration.objects.create(
            user=user, receipt=receipt, event=event, is_registration_approved=approval)
        event_reg.save()

        messages.add_message(request,
                             messages.SUCCESS,
                             'Your receipt/proof of payment was submitted successfully.')
        return redirect("/member/events/event/{}".format(event_id))


class EventsJoined(View):
    @method_decorator(login_required(login_url='/'))
    def get(self, request, *args, **kwargs):
        user = Profile.objects.get(id=request.user.profile.id)
        user_registered_events = EventRegistration.objects.filter(user=user)

        joined_events_filter = EventsJoinedFilter(
            request.GET, queryset=user_registered_events)
        user_registered_events = joined_events_filter.qs

        return render(request, template_name='member/events-joined.html', context={'user_registered_events': user_registered_events, 'joined_events_filter': joined_events_filter})


class Transactions(View):
    @method_decorator(login_required(login_url='/'))
    def get(self, request, *args, **kwargs):
        user = Profile.objects.get(id=request.user.profile.id)
        transactions = EventRegistration.objects.filter(
            user=user).order_by('-date_created')

        transactions_filter = EventsJoinedFilter(
            request.GET, queryset=transactions)
        transactions = transactions_filter.qs

        return render(request, template_name='member/transactions.html', context={'transactions': transactions, 'transactions_filter': transactions_filter})

member/templates/member/events-joined.html
{% extends 'member/base.html' %}
{% load static %}

{% block title %}
EVEREST | Events Joined
{% endblock %}

{% block content %}
<style>
#id_search_fields {
  width: 9em !important;
}

#id_cost {
  width: 4.2em !important;
}

#id_event_type {
  width: 8.5em !important;
}

#id_approval {
  width: 7em !important;
}
</style>

<main class="container-fluid">

  <form method="GET" class="form-control container-fluid mb-3 p-3" style="border: none;">
    <div class="container-fluid row" style="align-items: center; text-align: center;">
      <div class="form-group col-md-4">
        <label for="id_name">Keyword: </label><br>
        {{ joined_events_filter.form.search_fields }}
      </div>

      <div class="form-group col-md-1">
        <label for="id_cost">Price: </label><br>
        {{ joined_events_filter.form.cost }}
      </div>

      <div class="form-group col-md-2">
        <label for="id_event_type">Type: </label><br>
        {{ joined_events_filter.form.event_type }}
      </div>

      <div class="form-group col-md-2">
        <label for="id_event_type">Status: </label><br>
        {{ joined_events_filter.form.approval }}
      </div>

      <div class="form-group col container">
        <button class="btn btn-secondary"
          style="font-weight: bold; background-color: rgba(34, 166, 170, 0.918); border: none;"
          type="submit">SEARCH</button>
      </div>
    </div>
  </form>

  <section class="container container-fluid">
    <div class="row">
      {% for event in user_registered_events %}

      
      <div class="col container-fluid col-md-4 my-2">
        <div
          class="shadow mb-5 h-100 card card-item-event {% if event.event.event_type == 'CONFERENCE' %}card-header-conference{% elif event.event.event_type == 'SEMINAR' %}card-header-seminar{% else %}card-header-workshop{% endif %}"
          style="align-items: center; text-align: center; border: none;">
          <h3 class="card-header brand text-white" style="text-transform: uppercase;">{{ event.event.event_name }}</h3>
          <div class="card-body" style="background-color: aliceblue; width: 100%;">
            <h5 class="card-title">{{ event.event.short_description }}</h5>
            <p class="card-text" style="font-size: 0.8em;">
              <span style="text-transform: uppercase;">{{ event.event.date }}</span>
              <br>
              {{ event.event.location }}
            </p>
            <p class="card-text" style="font-weight: bold;">{{ event.event_type }}</p>

            <p class="card-text">
              {{ event.event.cost }} {{ event.event.price }}<br>
            </p>
            <br>

            <a href="/member/events/event/{{ event.event.id }}" class="btn btn-details mb-2">MORE DETAILS</a>
          </div>
        </div>
      </div>
     

      {% endfor %}
    </div>
  </section>

</main>

{% endblock %}

member/templates/member/find-event.html
{% extends 'member/base.html' %}
{% load static %}

{% block title %}
EVEREST | Find Events
{% endblock %}

{% block content %}

<main class="container-fluid">

  <form method="GET" class="form-control container-fluid mb-3 p-3" style="border: none;">
    <div class="container-fluid row" style="align-items: center; text-align: center;">
      <div class="form-group col-md-4">
        <label for="id_name">Keyword: </label>
        {{ find_event_filter.form.search_fields }}
      </div>

      <div class="form-group col-md-2">
        <label for="id_cost">Price: </label>
        {{ find_event_filter.form.cost }}
      </div>

      <div class="form-group col-md-3">
        <label for="id_event_type">Type: </label>
        {{ find_event_filter.form.event_type }}
      </div>

      <div class="form-group col container">
        <button class="btn btn-secondary" style="font-weight: bold; background-color: rgba(34, 166, 170, 0.918); border: none;"
          type="submit">SEARCH</button>
      </div>
    </div>
  </form>
  
    <section class="container container-fluid">
      <div class="row">
        {% for event in events %}

          {% if event.is_registration_open and event.id not in user_registered_events_approved %}
            <div class="col container-fluid col-md-4 my-2">
              <div class="shadow mb-5 h-100 card card-item-event {% if event.event_type == 'CONFERENCE' %}card-header-conference{% elif event.event_type == 'SEMINAR' %}card-header-seminar{% else %}card-header-workshop{% endif %}" style="align-items: center; text-align: center; border: none;">
                <h3 class="card-header brand text-white" style="text-transform: uppercase;">{{ event.event_name }}</h3>
                <div class="card-body" style="background-color: aliceblue; width: 100%;">
                  <h5 class="card-title">{{ event.short_description }}</h5>
                  <p class="card-text" style="font-size: 0.8em;">
                    <span style="text-transform: uppercase;">{{ event.date }}</span>
                    <br>
                    {{ event.location }}
                  </p>
                  <p class="card-text" style="font-weight: bold;">{{ event.event_type }}</p>
              
                  <p class="card-text">
                    {{ event.cost }} {{ event.price }}<br>
                  </p>
                  <br>
              
                  <a href="/member/events/event/{{ event.id }}" class="btn btn-details mb-2">MORE DETAILS</a>
                </div>
              </div>
            </div>
          {% endif %}

        {% endfor %}
      </div>
    </section>

</main>

{% endblock %}

member/templates/member/paid-registration-form.html
{% extends 'member/base.html' %}
{% load static %}

{% block title %}
EVEREST | Event Registration Transaction Form
{% endblock %}

{% block content %}

<style>
  upload-image-receipt {
    min-height: 20em;
  }
</style>

<main class="">

  <!-- start Popup -->
  {% for message in messages %}
    {% if form.errors %}
      {% for field in form %}
        {% for error in field.errors %}
          <div class="alert alert-danger alert-dismissible"
            style="z-index: 2; background-color: #C0392B; position: absolute; margin-left: 2em; right: 2em; top: 8em;">
            <strong>{{ error|escape }}</strong>
            <button type="button" class="close btn btn-interact text-white" data-dismiss="alert"
              style="position: absolute; top:0; right: -2.7em;"><i class="far fa-times-circle fa-1x text-white"></i></button>
          </div>
        {% endfor %}
      {% endfor %}
    {% endif %}
    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
      <p class="alert alert-danger alert-link alert-dismissible text-white"
        style="z-index: 2; background-color: #C0392B; position: absolute; margin-left: 2em; right: 2em; top: 8em;">
        {{ message }}
        <button type="button" class="close btn btn-interact" data-dismiss="alert"
          style="position: absolute; top:0; right: -2.7em;"><i class="far fa-times-circle fa-1x text-white"></i></button>
      </p>
    {% else %}
      <p class="alert alert-success alert-link alert-dismissible text-white"
        style="z-index: 2; background-color: #27AE60; position: absolute; margin-left: 2em; right: 2em; top: 8em;">
        {{message}}
        <button type="button" class="close btn btn-interact" data-dismiss="alert"
          style="position: absolute; top:0; right: -2.7em;"><i class="far fa-times-circle fa-1x text-white"></i></button>
      </p>
    {% endif %}
  {% endfor %}
  <!-- end Popup -->

  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-group row" style="margin-left: 1em;">
      <div class="form-group row">
        <div class="col-md" style="margin-top:0.5rem; margin-bottom:0.5rem;">
          <h5>Attachment for receipt/proof of payment subject to verification:</h5>
          <p><i><b>Note:</b> This upload form only accepts images.</i></p>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md" style="margin-top:0.5rem; margin-bottom:0.5rem;">
          <input type="file" name="receipt" accept="image/*" class="form-control upload-image-receipt" id="id_receipt" required>
          <img id="image" class="my-2" style="width: 100%; object-fit: cover; align-self: center;"/>
          <div id="placeholderdiv" style="background-color: rgb(219, 225, 226); width: 100%; height: 20em; text-align: center; display: flex; align-items: center; justify-content: center;">
            <h6 style="font-weight: bold;">Attachment Preview</h6>
          </div>

        </div>
      </div>
      <div class="form-group row my-3">
        <div class="col-md">
          <button type="submit" class="btn btn-warning form-control text-white" style="font-weight: 800;">SUBMIT FOR APPROVAL</button>
        </div>
      </div>
    </div>
  </form>

</main>

<script>
  document.getElementById('id_receipt').onchange = function () {
      var src = URL.createObjectURL(this.files[0])
      document.getElementById('image').src = src
      document.getElementById('placeholderdiv').style.display = "none";
    }
</script>

{% endblock %}

member/templates/member/transactions.html
{% extends 'member/base.html' %}
{% load static %}

{% block title %}
EVEREST | All Transactions
{% endblock %}

{% block content %}
<style>
  #id_search_fields {
    width: 9em !important;
  }

  #id_cost {
    width: 4.2em !important;
  }

  #id_event_type {
    width: 8.5em !important;
  }

  #id_approval {
    width: 7em !important;
  }
</style>

<main class="container-fluid">
  <section class="container container-fluid">
    <h1 class="text-center" style="font-weight: bold;">ALL TRANSACTIONS</h1>
    <hr class="my-4">
  </section>

  <form method="GET" class="form-control container-fluid mb-3 p-3" style="border: none;">
    <div class="container-fluid row" style="align-items: center; text-align: center;">
      <div class="form-group col-md-4">
        <label for="id_name">Keyword: </label><br>
        {{ transactions_filter.form.search_fields }}
      </div>

      <div class="form-group col-md-1">
        <label for="id_cost">Price: </label><br>
        {{ transactions_filter.form.cost }}
      </div>

      <div class="form-group col-md-2">
        <label for="id_event_type">Type: </label><br>
        {{ transactions_filter.form.event_type }}
      </div>

      <div class="form-group col-md-2">
        <label for="id_event_type">Status: </label><br>
        {{ transactions_filter.form.approval }}
      </div>

      <div class="form-group col container">
        <button class="btn btn-secondary"
          style="font-weight: bold; background-color: rgba(34, 166, 170, 0.918); border: none;"
          type="submit">FILTER</button>
      </div>
    </div>
  </form>

  <section class="">
    <div>
      <table id="qlist" style="width: 100%;">
        <thead>
          <th>
            TID
          </th>
          <th>
            EVENT
          </th>
          <th>
            DATE
          </th>
          <th>
            DESCRIPTION
          </th>
          <th>
            STATUS
          </th>
        </thead>
    
        {% for transaction in transactions %}
        <tr>
          <td>{{ transaction.id }}</td>
          <td><a style="text-decoration: none; color: black; font-weight: bold;" href="/member/events/event/{{ transaction.event.id }}">{{ transaction.event.event_name }}</a></td>
          <td>{{ transaction.date_created }}</td>
          <td>{{ transaction.event.short_description }}</td>
          <td class="{% if transaction.is_registration_approved == 'APPROVED' %}bg-success{% elif transaction.is_registration_approved == 'PENDING' %}bg-primary{% else %}bg-danger{% endif %}" style="text-align: center; color: white;">{{ transaction.is_registration_approved }}</td>
        </tr>
        {% endfor %}
    
      </table>
    </div>
  </section>

</main>

<script>
  $(document).ready(function () {
    $('#qlist').DataTable({
      dom: 'Bfrltip',
      buttons: [
        {
          extend: 'csv',
          text: 'CSV',
          className: 'btn btn-default',
        },
        {
          extend: 'excel',
          text: 'Excel',
          className: 'btn btn-default',
        },
        {
          extend: 'pdf',
          text: 'PDF',
          className: 'btn btn-default',
        },
        {
          extend: 'print',
          text: 'Print',
          className: 'btn btn-default',
        },
      ],
      "lengthMenu": [[5, 10, 50, -1], [5, 10, 50, "All"]],
      "pagingType": "full_numbers",
      "pageLength": 10,
      "scrollX": true
    });
  });
</script>

{% endblock %}